### ISSUE TITLE
Illegal file name character on Windows

### ISSUE THREAD

**Issue by NickGaens** [wimleers/QEventLogger#1]
I've discovered a small bug, using this code on Windows.

On line 6, QDateTime::currentDateTime().toString(Qt::ISODate) contains the "illegal" file name character ':', since the exported format is "YYYY-MM-DDTHH:MM:SS".

Changing this to .toString("yyyy-MM-ddTHH-MM-ss") resolves this issue.

**Comment by wimleers** [comment]
Windows filenames don't support semi-colons. Closed by 7d0006eaea401c298b85493bf6b1f5ffce83aae1.

**Comment by wimleers** [comment]
(I opted to use .replace(":", "-") instead, so that I didn't have to define a custom date format.)
